[profile.default]
ast = true
build_info = true
extra_output = ["storageLayout"]
ffi = true
libs = ["lib"]
out = "out"
solc = "0.8.25"
src = "src"
via_ir = true

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4

[rpc_endpoints] # test on local anvil which forked sepolia
default = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
